### PR TITLE
Fix stdlib dependency errors

### PR DESCRIPTION
**Pull request by jasonkena**

### CODE REVIEW

**Comment by william-silversmith** [comment]
Thank you Jason! What platform had the errors? Will merge this soon.

**Comment by jasonkena** [comment]
No problem! I was attempting to build this from source on a Linux system with gcc 11.1.0, to compile the DracoPy library.

**Comment by william-silversmith** [comment]
Can you tell me a little bit more? DracoPy has precompiled binaries for linux (manylinux2010): https://pypi.org/project/DracoPy/1.0.1/#files

Which python version and pip version are you using? Is it musllinux?

**Comment by jasonkena** [comment]
Ah, that must be it. There are no binaries for Python 3.10 yet. I'm using pip 21.3.1 on Arch.

**Comment by william-silversmith** [comment]
I'll look into making some 3.10. I think I was waiting for 3.6 EOL first for simplicity's sake since the new GHA cibuildwheels dont make 3.6.

**Comment by william-silversmith** [comment]
I just uploaded an x86 manylinux wheel for py310 check it out!

**Pull request merged**
